### ISSUE TITLE
'GIMSK' was not declared in this scope

### ISSUE THREAD

**Issue by Zwedgy** [J-Rios/Digispark_SoftSerial-INT0#1]
I cant even import the`<SoftSerial_INT0.h>` library. I just get this error when compiling:
`Arduino15\packages\digistump\hardware\avr\1.6.7\libraries\DigisparkSoftSerial_INT0\SoftSerial_INT0.cpp:319:3: error: 'GIMSK' was not declared in this scope`.
I am using Digispark Pro with Arduino IDE 1.6.9

**Comment by J-Rios** [comment]
This library is just for Digispark (Attiny85 microcontrollers); Digispark Pro (Attiny167) is not supported, that is why you are getting that "error".

**Comment by Zwedgy** [comment]
Is there a way I could modify that to work with the Digispark Pro. I tried replacing the `GIMSK `with `*digitalPinToPCMSK(_receivePin)`(along with MCUCR), because the Digispark Pro had `SoftSerial.cpp` using that. But the library didn't just work anymore after doing this. I couldn't even receive the serial data from my Bluetooth module.

**Comment by J-Rios** [comment]
But why you need this library in Digispark Pro? you have hardware UART pins available that doesn't conflict with USB communiation, instead of use this library, just use pins PA0/6 (Rx) and PA1/7 (Tx) to connect the bluetooth module and use "Serial" object in the code to talk to the bluetooth...
